### ISSUE TITLE
OutOfMemoryError on java.lang.AbstractStringBuilder.enlargeBuffer 

### ISSUE THREAD

**Issue by danvinokour** [tony19/logback-android#103]
Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
       at java.lang.StringBuilder.append(StringBuilder.java:216)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.subjoinExceptionMessage(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.subjoinFirstLine(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.recursiveAppend(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.recursiveAppend(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.recursiveAppend(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.throwableProxyToString(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.convert(Unknown Source)
       at ch.qos.logback.classic.pattern.ThrowableProxyConverter.convert(Unknown Source)
       at ch.qos.logback.core.pattern.FormattingConverter.write(Unknown Source)
       at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(Unknown Source)
       at ch.qos.logback.classic.PatternLayout.doLayout(Unknown Source)
       at ch.qos.logback.classic.PatternLayout.doLayout(Unknown Source)
       at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.writeOut(Unknown Source)
       at ch.qos.logback.core.FileAppender.writeOut(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.FileAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.append(Unknown Source)
       at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
       at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.callAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Unknown Source)
       at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Unknown Source)
       at ch.qos.logback.classic.Logger.error(Unknown Source)

**Comment by tony19** [comment]
There's not enough info here. What are the contents of the string being logged? What's your logback version and config?

**Comment by danvinokour** [comment]
its 1.1.1-3 with slf4j-api:1.7.6.

I dont know the string yet becouse it is an exception coming from the server and we will have it monitored only in the next version which comes out in about two weeks.

**Comment by tony19** [comment]
This doesn't appear to be a bug with logback-android and is not reproducible.
