### ISSUE TITLE
Log file name is not creating for the first time on app launch

### ISSUE THREAD

**Issue by nAkhmedov** [tony19/logback-android#145]
How is it possible to create folder if it is not exist like creating log file? 
```
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,897 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [assets/logback.xml] at [assets/logback.xml]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,913 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,915 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,915 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [logcat]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,919 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,929 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,929 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MainLog]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,936 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,954 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,954 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /mnt/sdcard/Android/data/package_name/files/data/logs/main_%d{yyMMdd}.log for the active file
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,957 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyMMdd' from file name pattern '/mnt/sdcard/Android/data/package_name/files/data/logs/main_%d{yyMMdd}.log'.
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,957 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,958 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Jun 08 23:05:00 EDT 2017
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,958 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MainLog] - Active log file name: /mnt/sdcard/Android/data/package_name/files/data/logs/main.log
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,959 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MainLog] - File property is set to [/mnt/sdcard/Android/data/package_name/files/data/logs/main.log]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,961 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[MainLog] - Failed to create parent directories for [/mnt/sdcard/Android/data/package_name/files/data/logs/main.log]
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,961 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[MainLog] - openFile(/mnt/sdcard/Android/data/package_name/files/data/logs/main.log,true) failed java.io.FileNotFoundException: /mnt/sdcard/Android/data/package_name/files/data/logs/main.log (No such file or directory)
06-08 23:05:01.002 15895 15895 I System.out: 	at java.io.FileNotFoundException: /mnt/sdcard/Android/data/package_name/files/data/logs/main.log (No such file or directory)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at java.io.FileOutputStream.open(Native Method)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.FileAppender.openFile(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.FileAppender.start(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.impl.StaticLoggerBinder.getSingleton(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.LoggerFactory.bind(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.LoggerFactory.performInitialization(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.LoggerFactory.getILoggerFactory(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.LoggerFactory.getLogger(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at org.slf4j.LoggerFactory.getLogger(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at package_name.ShazzleMobileApplication.<init>(Unknown Source)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at java.lang.Class.newInstance(Native Method)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.Instrumentation.newApplication(Instrumentation.java:1015)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.Instrumentation.newApplication(Instrumentation.java:1000)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.LoadedApk.makeApplication(LoadedApk.java:835)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5944)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.os.Looper.loop(Looper.java:154)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at android.app.ActivityThread.main(ActivityThread.java:6776)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at java.lang.reflect.Method.invoke(Native Method)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
06-08 23:05:01.002 15895 15895 I System.out: 	at 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,962 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
```

**Comment by nAkhmedov** [comment]
`<configuration>
    <property name="LOG_DIR" value="/mnt/sdcard/Android/data/package_name/files/data/logs" />

    
    <appender name="logcat" class="ch.qos.logback.classic.android.LogcatAppender">
        <encoder>
            <pattern>%msg</pattern>
        </encoder>
    </appender>

    
    <appender name="MainLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
        
        <prudent>true</prudent>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_DIR}/main_%d{yyMMdd}.log</fileNamePattern>
            <maxHistory>4</maxHistory>
            <totalSizeCap>100MB</totalSizeCap>
        </rollingPolicy>
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    
    <appender name="ErrorLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
        

        <prudent>true</prudent>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_DIR}/error_%d{yyMMdd}.log</fileNamePattern>
            <maxHistory>4</maxHistory>
            <totalSizeCap>100MB</totalSizeCap>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>

        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>ERROR</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
    </appender>

    
    <root level="INFO">
        <appender-ref ref="logcat" />
        <appender-ref ref="ErrorLog" />
        <appender-ref ref="MainLog" />
    </root>
</configuration>
`

**Comment by HenningL** [comment]
Having the same issue. Is there a workaround?

**Comment by tony19** [comment]
According to your log, the parent directories cannot be created:

```
06-08 23:05:01.002 15895 15895 I System.out: 23:05:00,961 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[MainLog] - openFile(/mnt/sdcard/Android/data/package_name/files/data/logs/main.log,true) failed java.io.FileNotFoundException: /mnt/sdcard/Android/data/package_name/files/data/logs/main.log (No such file or directory)
```

Yes, normally `logback-android` will automatically create parent directories of a log file, but you must have write permissions to the file path. If, for instance, you're trying to create a directory off of `/` (e.g., create `/mnt`), you will run into a permissions error because only `root` can create files/directories off of `/`. Perhaps you meant to write to your app's data directory, which is at `${DATA_DIR}` (this is a special variable in `logback.xml` that points to `/data/data/${PACKAGE_NAME}/files`).

If this is not a permissions issue, please comment and we can reopen this issue.
