### ISSUE TITLE
Multidex : ClassNotFoundException

### ISSUE THREAD

**Issue by mgohin** [tony19/logback-android#159]
Hi,

we work on multiple devices but we have a problem with the one (and only) on Android 4.3 (Unitec PA700), when we use the `debug` variant, we can't make Logback working because of a ClassNotFoundException at runtime. I have this CNFE for all appenders used in my logback file (I renamed the project to x.y.z here).

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "ch.qos.logback.core.rolling.RollingFileAppender" on path: DexPathList[[zip file "/data/app/x.y.z.dev-1.apk"],nativeLibraryDirectories=[/data/app-lib/x.y.z.dev-1, /vendor/lib, /system/lib]]
01-04 13:50:49.424 25278-25278/x.y.z.dev I/System.out:     at 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
01-04 13:50:49.424 25278-25278/x.y.z.dev I/System.out:     at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
01-04 13:50:49.424 25278-25278/x.y.z.dev I/System.out:     at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
```
When using `release` variant, all is OK.
On android >= 5 all works great.

We are using MultiDex, we tried without and without a config file (with config file, those "missing" classes are in the first dex file).

`multidex-config.text`
```ch/qos/logback/classic/android/LogcatAppender.class
ch/qos/logback/core/rolling/RollingFileAppender.class
````

`proguard-rules.pro`
```-dontwarn ch.qos.logback.**
-keep class  ch.qos.logback.** { *; }
-keep interface ch.qos.logback.** { *; }
```

`build.config`
```
android {
    defaultConfig {
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexKeepFile file('multidex-config.txt')
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexKeepFile file('multidex-config.txt')
        }
    }
}
```
Do you have any idea ?

**Comment by mgohin** [comment]
Found it !

I have to use `multiDexKeepProguard file('multidex-proguard-rules.pro')` instead of `multiDexKeepFile file('multidex-config.txt')`

`build.config`
```
android {
    defaultConfig {
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexKeepFile file('multidex-config.txt')
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexKeepProguard file('multidex-proguard-rules.pro')
        }
    }
}
```

`multidex-proguard-rules.pro`
```
-dontwarn ch.qos.logback.**
-keep class  ch.qos.logback.** { *; }
-keep interface ch.qos.logback.** { *; }
```
