### ISSUE TITLE
Crash due to race condition when creating log directory

### ISSUE THREAD

**Issue by onomated** [tony19/logback-android#168]
Got crash report in Fabric:
```
Caused by java.lang.IllegalStateException: /storage/emulated/0/app_name/logs/app_name-latest.log should not have existing parent directory
       at ch.qos.logback.core.util.FileUtil.createMissingParentDirectories(Unknown Source)
       at ch.qos.logback.core.FileAppender.openFile(Unknown Source)
       at ch.qos.logback.core.FileAppender.start(Unknown Source)
       at ch.qos.logback.core.rolling.RollingFileAppender.start(Unknown Source)
...
```
Upon investigation, this issue has since been addressed in logback upstream, see [JIRA issue](https://jira.qos.ch/browse/LOGBACK-128) and corresponding [patch](https://jira.qos.ch/secure/attachment/10277/parent_dirs.patch)

Needs to be applied to https://github.com/tony19/logback-android/blob/master/logback-android/src/main/java/ch/qos/logback/core/util/FileUtil.java#L53

**Comment by tony19** [comment]
Fixed in [v_1.1.3-1](https://github.com/tony19/logback-android/releases/tag/v_1.1.3-1)
