### ISSUE TITLE
java.io.IOException: write failed: ENOTCONN (Transport endpoint is not connected)

### ISSUE THREAD

**Issue by nikialeksey** [tony19/logback-android#169]
Hello! I use `logback-android` 1.1.1-6. In my crashlytics I often got this non-fatal exceptions:
```
java.io.IOException: write failed: ENOTCONN (Transport endpoint is not connected)
       at libcore.io.IoBridge.write(IoBridge.java:533)
       at java.io.FileOutputStream.write(FileOutputStream.java:186)
       at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
       at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
       at ch.qos.logback.core.recovery.ResilientOutputStreamBase.flush(Unknown Source)
       at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.writeOut(Unknown Source)
       at ch.qos.logback.core.FileAppender.writeOut(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.FileAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.append(Unknown Source)
       at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
       at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.callAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Unknown Source)
       at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Unknown Source)
       at ch.qos.logback.classic.Logger.debug(Unknown Source)
```

```
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.my.package/files/logs/latest.log: open failed: ENOTCONN (Transport endpoint is not connected)
       at libcore.io.IoBridge.open(IoBridge.java:487)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
       at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(Unknown Source)
       at ch.qos.logback.core.FileAppender.openFile(Unknown Source)
       at ch.qos.logback.core.rolling.RollingFileAppender.rollover(Unknown Source)
       at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(Unknown Source)
       at ch.qos.logback.core.OutputStreamAppender.append(Unknown Source)
       at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
       at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.callAppenders(Unknown Source)
       at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Unknown Source)
       at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Unknown Source)
       at ch.qos.logback.classic.Logger.info(Unknown Source)
```

**Comment by cyph3rcod3r** [comment]
What is the resolution for that?

**Comment by tony19** [comment]
Can you provide steps to reproduce?
