### ISSUE TITLE
Android Studio 3.1 - Failed to resolve: com.github.tony19:logback-android:1.1.1-10

### ISSUE THREAD

**Issue by ddelapaz** [tony19/logback-android#170]
After updating to the latest android studio `logback-android` wont compile.

Using the following on my gradle 4.4:
```
    implementation 'org.slf4j:slf4j-api:1.7.25'
    implementation 'com.github.tony19:logback-android:1.1.1-10'

```
The exception I found from`idea.log`,, not entirely sure if it's related.
```

2018-03-28 09:58:28,590 [d thread 5]   INFO -  #git4idea.commands.GitHandler - [DeliveryTracker-TC75] git -c core.quotepath=false -c log.showSignature=false rm --ignore-unmatch --cached -- .idea/libraries/Gradle__com_github_tony19_apktool_lib_1_4_4_3_jar.xml .idea/libraries/Gradle__com_github_tony19_logback_android_classic_1_1_1_6_jar.xml 
2018-03-28 09:58:28,844 [d thread 1]   INFO - agnostic.FrequentEventDetector - Too many events posted, #2. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=javax.swing.RepaintManager$ProcessingRunnable@6d5862da,notifier=null,catchExceptions=false,when=1522249108844] on sun.awt.windows.WToolkit@66d0d6f7
java.lang.Throwable
	at com.intellij.openapi.diagnostic.FrequentEventDetector.getMessageOnEvent(FrequentEventDetector.java:79)
	at com.intellij.ide.IdeEventQueue.doPostEvent(IdeEventQueue.java:1157)
	at com.intellij.ide.IdeEventQueue.postEvent(IdeEventQueue.java:1148)
	at javax.swing.RepaintManager.scheduleProcessingRunnable(RepaintManager.java:1444)
	at javax.swing.RepaintManager.addDirtyRegion0(RepaintManager.java:466)
	at javax.swing.RepaintManager.addDirtyRegion(RepaintManager.java:488)
	at javax.swing.JComponent.repaint(JComponent.java:4793)
	at java.awt.Component.repaint(Component.java:3362)
	at java.awt.Component.repaintParentIfNeeded(Component.java:2338)
	at java.awt.Component.reshape(Component.java:2326)
	at javax.swing.JComponent.reshape(JComponent.java:4207)
	at java.awt.Component.setBounds(Component.java:2269)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel$InlineLayout.layoutContainer(InfoAndProgressPanel.java:574)
	at java.awt.Container.layout(Container.java:1511)
	at java.awt.Container.doLayout(Container.java:1500)
	at java.awt.Container.validateTree(Container.java:1696)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validate(Container.java:1631)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
 

```

**Comment by tony19** [comment]
Sorry, I've just released it on Sonatype. It may take an hour before it's visible to you.

**Comment by ddelapaz** [comment]
Not a problem, thank you so much!
