### ISSUE TITLE
Null pointer if VersionName not set

### ISSUE THREAD

**Issue by marcuspridham** [tony19/logback-android#177]
This seems to have been broken by commit 10d35f73fed0d0b52a4b0a20205c73ab8279d3f4 (introduced in `v1.1.1-11`).  If the application does not have a `versionName` set, the `LoggerContext` can't be setup properly.

```
W/System.err: Failed to instantiate [ch.qos.logback.classic.LoggerContext]
    Reported exception:
    java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:461)
W/System.err:     at java.util.Properties.setProperty(Properties.java:161)
        at ch.qos.logback.core.android.AndroidContextUtil.setupProperties(Unknown Source:49)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:12)
        at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source:7)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source:20)
```

**Comment by tony19** [comment]
Fixed in [`v_1.1.1-12`](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-12)
