### ISSUE TITLE
Getting ANR 

### ISSUE THREAD

**Issue by abhinavgitaccount** [tony19/logback-android#192]
Geting ANR in android device (JellyBean4.3) while using logger, 
Please find the logs

-------------------

"Binder_7" prio=5 tid=43 VMWAIT JIT
  | group="main" sCount=1 dsCount=0 obj=0x6f339d48 self=0x79798c98
  | sysTid=4009 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=2034708968
  | state=S schedstat=( 0 0 0 ) utm=49 stm=7 core=1
  #00  pc 0001c58c  /vendor/lib/libc.so (__futex_syscall3+8)
  #01  pc 0000e6a8  /vendor/lib/libc.so (__pthread_cond_timedwait_relative+48)
  #02  pc 0000e708  /vendor/lib/libc.so (__pthread_cond_timedwait+64)
  #03  pc 00029d04  /system/lib/libdvm.so (dvmWaitForConcurrentGcToComplete()+180)
  #04  pc 00029f10  /system/lib/libdvm.so (dvmMalloc(unsigned int, int)+288)
  #05  pc 00068607  /system/lib/libdvm.so
  #06  pc 000063d1  /dev/ashmem/dalvik-jit-code-cache (deleted)
  at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:~94)
  at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
  at java.lang.StringBuilder.append(StringBuilder.java:124)
  at java.util.AbstractCollection.toString(AbstractCollection.java:382)
  at java.lang.StringBuilder.append(StringBuilder.java:202)
  at com.model.product.configuration.TestConfig.toString(TestConfig.java:836)
  at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:299)
  at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:271)
  at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:233)
  at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:173)
  at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage((null):-1)
  at ch.qos.logback.classic.pattern.MessageConverter.convert((null):-1)
  at ch.qos.logback.classic.pattern.MessageConverter.convert((null):-1)
  at ch.qos.logback.core.pattern.FormattingConverter.write((null):-1)
  at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters((null):-1)
  at ch.qos.logback.classic.PatternLayout.doLayout((null):-1)
  at ch.qos.logback.classic.PatternLayout.doLayout((null):-1)
  at ch.qos.logback.classic.android.LogcatAppender.append((null):-1)
  at ch.qos.logback.classic.android.LogcatAppender.append((null):-1)
  at ch.qos.logback.core.AppenderBase.doAppend((null):-1)
  at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders((null):-1)
  at ch.qos.logback.classic.Logger.appendLoopOnAppenders((null):-1)
  at ch.qos.logback.classic.Logger.callAppenders((null):-1)
  at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend((null):-1)
  at ch.qos.logback.classic.Logger.filterAndLog_1((null):-1)
  at ch.qos.logback.classic.Logger.debug((null):-1)
----------------------

**Comment by tony19** [comment]
Can you provide a GitHub repo that reproduces the problem?

**Comment by tony19** [comment]
Let me know if you can provide reproduction steps, and we can reopen to investigate.

**Comment by abhinavgitaccount** [comment]
There is one deadlock fixed in logcat appender and it is released  in 1.1.1-5 is this version for logback or slf4j
https://github.com/tony19/logback-android/issues/104
