### ISSUE TITLE
LogcatAppender should add newline between message and exception 

### ISSUE THREAD

**Issue by pischky** [tony19/logback-android#215]
## Description

When using ch.qos.logback.classic.android.LogcatAppender with Throwable a newline should be added

## Steps to reproduce
````
Throwable ex = new IllegalStateException("Test exception");
log.error("message", ex);`
````
````
<appender name="LOGCAT" class="ch.qos.logback.classic.android.LogcatAppender">
        <tagEncoder>
            <pattern>%logger{0}</pattern>
        </tagEncoder>
        <encoder>
            <pattern>[%thread] %msg</pattern>
        </encoder>
</appender>
````

### Current
````
2020-05-10 10:47:33.984 13753-13799/de.pischky.flog.mde E/LoggingTest: [Instr: androidx.test.runner.AndroidJUnitRunner] messagejava.lang.IllegalStateException: Test exception
        at de.pischky.android.LoggingTest.exceptionTest(LoggingTest.java:67)
        at java.lang.reflect.Method.invoke(Native Method)
        ...
````
### Expected
````
2020-05-10 10:47:33.984 13753-13799/de.pischky.flog.mde E/LoggingTest: [Instr: androidx.test.runner.AndroidJUnitRunner] message
java.lang.IllegalStateException: Test exception
        at de.pischky.android.LoggingTest.exceptionTest(LoggingTest.java:67)
        at java.lang.reflect.Method.invoke(Native Method)
        ...
````
RollingFileAppender has this output.

## Environment

* **`logback-android` version:** 2.0.0
* **Android version:** 8.1 ??
* **Platform:** Honeywell EDA51

**Comment by pischky** [comment]
Not solved until today.
How can I help to solve this?
